
<template>
    
    <div class="w-screen h-screen bg-main text-maintext text-4xl flex justify-center items-center flex-col relative overflow-x-hidden overflow-y-hidden">
        <Navbar></Navbar>
        <div class="relative ">
            <div class="mb-16 font text-[6.5rem] animated slideInDown">
                SAM CHANG
            </div>
            <div class="mb-16 font2 text-[6.5rem]">
                UI / WEB
            </div>
            <div class="mb-16 font3 text-[6.5rem]">
                DESIGNER.
            </div>
            <div class="absolute top-0 -right-44 circle">
                <img src="../../assets/circle.png" alt="" class="w-2/3">
            </div>
        </div>
        <div class="scale-up-ver-center border rounded-full text-base px-16 py-6 cursor-pointer">
            gogogo
        </div>
    </div>
</template>

<style>
.font {
    font-family: supersize-bk, sans-serif;
    font-weight: 400;
    font-style: normal;
    opacity: 0;
    animation-name: font;
    animation-duration: 1s;
    animation-delay: 1s;
    animation-fill-mode: forwards;
    transition: transform 0.6s cubic-bezier(0, 0.55, 0.45, 1);
    
}

@keyframes font {
    50% {
        opacity: 1;
        transform: translate(0px, -50px)
    }

    100% {
        opacity: 1;
        transform: translate(0px, 0px)
    }
}

@keyframes font {
    0% {
        transform: scale(2);
    }

    50% {
        transform: scale(1);
    }
}

.font2 {
    font-family: supersize-bk, sans-serif;
    font-weight: 400;
    font-style: normal;
    opacity: 0;
    animation-name: font2;
    animation-duration: 1s;
    animation-delay: 1.4s;
    animation-fill-mode: forwards;
    transition: transform 0.6s cubic-bezier(0, 0.55, 0.45, 1);
}

@keyframes font2 {
    50% {
        opacity: 1;
        transform: translate(0px, -50px)
    }

    100% {

        opacity: 1;
        transform: translate(0px, 0px)
    }
}

@keyframes font2 {
    0% {
        transform: scale(2);
    }

    50% {
        transform: scale(1);
    }
}

.font3 {
    font-family: supersize-bk, sans-serif;
    font-weight: 400;
    font-style: normal;
    opacity: 0;
    animation-name: font3;
    animation-duration: 1s;
    animation-delay: 1.6s;
    animation-fill-mode: forwards;
    transition: transform 0.6s cubic-bezier(0, 0.55, 0.45, 1);
}

@keyframes font3 {
    50% {
        opacity: 1;
        transform: translate(0px, -50px)
    }

    100% {

        opacity: 1;
        transform: translate(0px, 0px)
    }
}

@keyframes font3 {
    0% {
        transform: scale(2);
    }

    50% {
        transform: scale(1);
    }
}

.circle {

    opacity: 0;
    animation-name: circle;
    animation-duration: 1s;
    animation-delay: 2.1s;
    animation-fill-mode: forwards;
    transition: transform 0.6s cubic-bezier(0, 0.55, 0.45, 1);

}

@keyframes circle {
    50% {
        opacity: 1;
        transform: translate(0px, -50px);
        
    }

    100% {
        opacity: 1;
        transform: translate(0px, 0px);
        
    }
}

@keyframes circle {
    0% {
        transform: scale(2);

    }

    50% {
        transform: scale(1);

    }
}


.scale-up-ver-center {
    -webkit-animation: scale-up-ver-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    animation: scale-up-ver-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    animation-delay: 1.8s;
    opacity: 0;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-9-26 15:27:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-ver-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-ver-center {
    0% {
        -webkit-transform: scaleY(0.4);
        transform: scaleY(0.4);

    }

    100% {
        -webkit-transform: scaleY(1);
        transform: scaleY(1);
    }
}

@keyframes scale-up-ver-center {
    0% {
        -webkit-transform: scaleY(0.4);
        transform: scaleY(0.4);
        opacity: 0;
    }

    100% {
        -webkit-transform: scaleY(1);
        transform: scaleY(1);
        opacity: 1;
    }
}
</style>


<script setup>
import Navbar from './navbar.vue';
</script>

<script>
(function (d) {
    var config = {
        kitId: 'asb7nqb',
        scriptTimeout: 3000,
        async: true
    },
        h = d.documentElement, t = setTimeout(function () { h.className = h.className.replace(/\bwf-loading\b/g, "") + " wf-inactive"; }, config.scriptTimeout), tk = d.createElement("script"), f = false, s = d.getElementsByTagName("script")[0], a; h.className += " wf-loading"; tk.src = 'https://use.typekit.net/' + config.kitId + '.js'; tk.async = true; tk.onload = tk.onreadystatechange = function () { a = this.readyState; if (f || a && a != "complete" && a != "loaded") return; f = true; clearTimeout(t); try { Typekit.load(config) } catch (e) { } }; s.parentNode.insertBefore(tk, s)
})(document);
</script>